- name: Build the application image and push it to the Google container registry
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    apptag: "v1.3"

  tasks:
  - name: Build an image and push it to a private repo
    docker_image:
      build:
        path: .
        nocache: yes
      name: asia.gcr.io/kubernetes-268302/hello-ansible
      tag: "{{ apptag }}"
      push: yes
      source: build

  - set_stats:
      data:
        apptag: "{{ apptag }}"
      per_host: no
