apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: hello-ansible
  name: hello-ansible
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-ansible
  type: LoadBalancer
status:
  loadBalancer: {}
