#kubectl expose deployment hello-ansible --port=80 --target-port=8080 --type=LoadBalancer --dry-run -o yaml > service.yml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: hello-ansible
  name: hello-ansible
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-ansible
  type: LoadBalancer
status:
  loadBalancer: {}
